<!-- Shiny logic and UI to check the results of the student-submitted answers -->

```{r input-name-example, echo = FALSE}
  question_text(
    "名前を書いてください",
    answer(NULL, correct = TRUE),
    incorrect = NULL,
    allow_retry = TRUE,
    try_again_button = "編集する"
  )
```

```{r input-id-example, echo = FALSE}
  question_text(
    "学籍番号を書いてください",
    answer(NULL, correct = TRUE),
    incorrect = NULL,
    allow_retry = TRUE,
    try_again_button = "編集する"
  )
```

```{r context="server"}
shiny::observeEvent(
  input$check,
  {
    # Extract all questions in tutorial
    # IMPORTANT: Exclude any with "example" in chunk label
    # (should not be included in grading)
    tutorial_info <- learnr::get_tutorial_info()
    questions <- tutorial_info$items[, c("order", "label", "type")] |>
      dplyr::filter(!stringr::str_detect(label, "-example")) |>
      dplyr::arrange("order")

    questions <- questions |>
      dplyr::mutate(order = seq_len(nrow(questions)))

    # Extract state of exercises (correct or not)
    # tutorial_state is list with one item per submitted exercise or question.
    # If it hasn't been submitted yet, it won't appear in the list
    tutorial_state <- learnr:::get_tutorial_state()

    # Extract answers (correct or incorrect) as dataframe
    if (length(tutorial_state) > 0) {
      answers <-
        tibble::tibble(
          label = names(tutorial_state),
          correct = purrr::map_chr(tutorial_state, "correct"),
          timestamp = purrr::map_chr(tutorial_state, "timestamp")
        )
    } else {
      answers <- tibble::tibble(
        label = questions$label,
        correct = NA_character_,
        timestamp = NA_character_
      )
    }

    # Extract name and student id
    if (length(tutorial_state) > 0) {
      student_name <- purrr::pluck(tutorial_state, "input-name-example", "answer")
      student_id <- purrr::pluck(tutorial_state, "input-id-example", "answer")
    } else {
      student_name <- NULL
      student_id <- NULL
    }

    # Combine questions and answers into summary
    summary <- dplyr::left_join(questions, answers, by = "label")

    # Format for nice printing in app
    summary_show <-
      summary |>
      dplyr::mutate(question = paste0("Q", order)) |>
      dplyr::select(question, label, result = correct, time = timestamp) |>
      dplyr::mutate(
        result = as.character(result) |>
          stringr::str_replace_all("TRUE", "✅") |>
          stringr::str_replace_all("FALSE", "❌") |>
          tidyr::replace_na(""),
        time = dplyr::case_when(
          result == "" ~ "",
          is.na(time) ~ "",
          .default = time
        )
      )
    
    # Format name feedback
    if (!is.null(student_name)) {
      student_name_text <- paste("Student name: ", student_name)
    } else {
      student_name_text <- "Student name: 名前を正しく入力してください"
    }

    # Format name feedback
    if (!is.null(student_id)) {
      student_id_text <- paste("Student ID: ", student_id)
    } else {
      student_id_text <- "Student ID: 学籍番号を正しく入力してください"
    }

    # Calculate current score
    n_correct <- sum(as.logical(summary$correct), na.rm = TRUE)
    n_total <- nrow(summary)
    score <- round(n_correct / n_total, 3) * 100
    score_text <- paste0(
      "You have answered ",
      n_correct,
      "/",
      n_total,
      " questions correctly. ",
      "Your score is "
      , score, "%."
    )

    # For debugging only
    output$state <- shiny::renderText(
      paste(
        capture.output(str(tutorial_state)),
        collapse = "\n"
      )
    )
    output$summary_table <- shiny::renderTable(summary_show)
    output$score_text <- shiny::renderText(score_text)
    output$student_name_text <- shiny::renderText(student_name_text)
    output$student_id_text <- shiny::renderText(student_id_text)
    invisible()
  }
)
```

**投稿する前に必ず答えと名前および学籍番号を確認してください:**

```{r state, echo=FALSE}
shiny::actionButton("check", "投稿内容を確認する")
shiny::br()
shiny::textOutput("student_name_text")
shiny::br()
shiny::textOutput("student_id_text")
shiny::br()
shiny::textOutput("score_text")
shiny::br()
shiny::tableOutput("summary_table")
# For debugging only
# learnrhash:::wrapped_verbatim_text_output("state")
```
